### ISSUE TITLE
near verions: 0.24.3 encoding issue

### ISSUE THREAD

**Issue by sundafa** [near/near-shell#432]
**Describe the bug**
near run error:
`/usr/bin/env: ‘node\r’: No such file or directory`

**To Reproduce**
1. update version `yarn global add near-shell`
2. run cmd `near`

**Screenshots**
![image](https://user-images.githubusercontent.com/24621599/85379813-c38c4000-b56e-11ea-9928-98c624e75b39.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version 0.24.3

**Additional context**
Executing the command has fixed the problem
`dos2unix /usr/local/share/.config/yarn/global/node_modules/near-shell/bin/near`

**Comment by bowenwang1996** [comment]
@mikedotexe can you take a look?

**Comment by mikedotexe** [comment]
> @mikedotexe can you take a look?

This is good timing, I have just noticed this about an hour ago and have been trying to track it down. It's related to a carriage return, probably introduced from Windows commits. Still hunting…

**Comment by mikedotexe** [comment]
Thank you @sundafa for the very helpful bug report. It's community members like you that make NEAR better every day. We've pushed [another version](https://github.com/near/near-shell/releases/tag/v0.24.4) (no actual changes or new commits) and the issue has been resolved. Turns out we published that version from a Windows machine and it included Windows-related line endings.
Thanks again. 🚀
